---

- name: "configuration play." 
  hosts: all
  user: ubuntu
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml
  roles:
    - role: weareinteractive.environment
      become: yes
    - role: deploy
      become: yes
  vars:
    environment_config:
    - ENVIRONMENT: production             
    - NODE_ENV: production
    - TYPEORM_ENTITIES: ./modules/domain/**/*.entity{.ts,.js}
    - TYPEORM_MIGRATIONS:  ./migrations/*.ts
    - TYPEORM_MIGRATIONS_DIR: ./migrations
    - TYPEORM_CONNECTION: "{{ lookup('env','TYPEORM_CONNECTION') }}"
    - TYPEORM_HOST: "{{ lookup('env','TYPEORM_HOST') }}"
    - TYPEORM_PORT: "{{ lookup('env','TYPEORM_PORT') }}"
    - TYPEORM_USERNAME: "{{ lookup('env','TYPEORM_USERNAME') }}"
    - TYPEORM_PASSWORD: "{{ lookup('env','TYPEORM_PASSWORD') }}"
    - TYPEORM_DATABASE: "{{ lookup('env','TYPEORM_DATABASE') }}"
